Back to WAF
Too much instability right now. Hopefully we can revisit autoconf soon.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,21 @@
-#!/bin/sh
+#! /bin/sh
 
-cd `dirname "$0"`
-autoconf --output configure.real
-exec ./configure.real "$@"
+# v8 doesn't like ccache
+if [ ! -z "`echo $CC | grep ccache`" ]; then
+  echo "Error: V8 doesn't like cache. Please set your CC env var to 'gcc'"
+  echo "  (ba)sh: export CC=gcc"
+  exit 1
+fi
 
+CUR_DIR=$PWD
+
+#possible relative path
+WORKINGDIR=`dirname $0`
+cd "$WORKINGDIR"
+#abs path
+WORKINGDIR=`pwd`
+cd "$CUR_DIR"
+
+"${WORKINGDIR}/tools/waf-light" --jobs=1 configure $*
+
+exit $?
