tools: add message on auto-fixing js lint issues in gh workflow

diff --git a/.github/workflows/linters.yml b/.github/workflows/linters.yml
--- a/.github/workflows/linters.yml
+++ b/.github/workflows/linters.yml
@@ -103,7 +103,20 @@ jobs:
       - name: Environment Information
         run: npx envinfo
       - name: Lint JavaScript files
-        run: NODE=$(command -v node) make lint-js
+        run: |
+          NODE=$(command -v node) make lint-js && true
+          EXIT_CODE="$?"
+          if [ "$EXIT_CODE" != "0" ]
+          then
+            echo
+            echo 'ERROR: The JavaScript lint validation failed (the errors are logged above).'
+            echo '       Please fix the lint errors.'
+            echo '       Run:'
+            echo '          make lint-js-fix'
+            echo '       to fix the auto-fixable lint issues.'
+            echo
+            exit "$EXIT_CODE"
+          fi
       - name: Get release version numbers
         if: ${{ github.event.pull_request && github.event.pull_request.base.ref == github.event.pull_request.base.repo.default_branch }}
         id: get-released-versions
