tools: fix Slack notification action

diff --git a/.github/workflows/notify-on-push.yml b/.github/workflows/notify-on-push.yml
--- a/.github/workflows/notify-on-push.yml
+++ b/.github/workflows/notify-on-push.yml
@@ -32,16 +32,19 @@ jobs:
     if: github.repository == 'nodejs/node'
     runs-on: ubuntu-latest
     steps:
+      - uses: actions/checkout@v3
+        with:
+          persist-credentials: false
       - name: Check commit message
-        run: npx -q core-validate-commit ${{ github.event.commits[0].id }} || echo "INVALID_COMMIT_MESSAGE=1" >> $GITHUB_ENV
+        run: npx -q core-validate-commit ${{ github.event.after }} || echo "INVALID_COMMIT_MESSAGE=1" >> $GITHUB_ENV
       - name: Retrieve PR number if possible
         if: ${{ env.INVALID_COMMIT_MESSAGE }}
         run: |
-          node <<<'EOF'
+          node <<'EOF' >> $GITHUB_ENV || true
           const invalidCommitMessageMatch = /\s\(\#\d+\)$/.exec(process.env.COMMIT_MESSAGE);
-          if (match == null) process.exit(1)
-          console.log(`PR_ID=${match[0]}`)
-          EOF >> $GITHUB_ENV || true
+          if (invalidCommitMessageMatch == null) process.exit(1)
+          console.log(`PR_ID=${invalidCommitMessageMatch[0]}`)
+          EOF
         env:
           COMMIT_MESSAGE: ${{ github.event.commits[0].message }}
       - name: Comment on the Pull Request
